groups: [course, intelligence, ]

club:
  ionlights: president
  sirroboto: vice-president
  aswu: advisor

course:
  ionlights: director
  brandons209: coordinator
  jarviseq: coordinator
  irene-l-tanner: coordinator
  danielzgsilva: coordinator
  cg021: coordinator
  ahkerrigan: coordinator

intelligence:
  ionlights: director
  waldmannly: director